### ISSUE TITLE
eyed3 adding images

### ISSUE THREAD

**Issue by mike-frontmen** [Jack12816/id3-writer#2]
When adding images to an MP3 I get the following output:

`eyeD3 --force-update --encoding utf8 -1 -2 -a "Gold Panda" -t "You" -A "Lucky Shiner" -Y 2015 -n 1 --add-image /Users/mike/Dropbox/development/spotifier/covers/Gold Panda - You.png:FRONT_COVER "//Users/mike/Dropbox/development/spotifier/tracks/Gold Panda - You.mp3"`

Error: Command failed: usage: eyeD3 [-h] [--version] [-l LEVEL[:LOGGER]] [--exclude PATTERN] [-L]`

The eyeD3 command should be:

`eyeD3 --force-update --encoding utf8 -1 -2 -a "Gold Panda" -t "You" -A "Lucky Shiner" -Y 2015 -n 1 --add-image "/Users/mike/Dropbox/development/spotifier/covers/Gold Panda - You.png":FRONT_COVER "//Users/mike/Dropbox/development/spotifier/tracks/Gold Panda - You.mp3"`

Simple fix:

lib/writer/eyeD3.js on line 228:

`image.getFile().getPath()`

should be:

`'"' + image.getFile().getPath() + '"'`

**Comment by Jack12816** [comment]
The problem should be fixed. I pushed a new version: 1.2.1.
Can you confirm the fix?

**Comment by mike-frontmen** [comment]
confirmed, working perfect :)

**Comment by Jack12816** [comment]
Great! Thank you for your contribution. :)
